services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=quran'
      - 'MYSQL_PASSWORD=user'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
  admin:
    environment:
      - PROFILE=local
    ports:
      - 8081:8081
  api:
    environment:
      - PROFILE=local
    ports:
      - 8080:8080