spring:
  datasource:
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/quran
    driver-class: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true