name: Build and tests on admin for pull request

on:
  pull_request:
    types:
      - opened
    paths:
      - 'admin/**.java'
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew :admin:build

      - name: Tests with Gradle Wrapper
        run: ./gradlew :admin:test
