name: Tests backend admin
run-name: Tests backend on api by @${{ github.actor }}

on:
  pull_request:
    paths:
      - 'api/**'
    branches:
      - dev

jobs:
  tests-backend-admin:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Tests with Gradle Wrapper
        run: ./gradlew :api:test
